version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: script/dockerfiles/Dockerfile.app
    ports:
      - "8080:8080"
    command: bash -c "yarn install && yarn start"
    volumes:
      - .:/work
